#!/bin/bash

MYWORLD=delta
export MYWORLD

sudo service spigot stop
overviewer.py --config=/minecraft/ovmyworld.py
overviewer.py --config=/minecraft/ovmyworld.py --genpoi
sudo service spigot start
sudo rm -rv /var/www/html/*
cp /minecraft/index.html /minecraft/mcmap/index.html 
sudo cp -Rv /minecraft/mcmap/* /var/www/html
sudo service httpd restart
